app:
  url: ${APP_URL}
  cors:
    allowed-origin-patterns: ${CORS_ALLOWED_ORIGIN_PATTERNS}
  security:
    jwt:
      private-key-path: ${JWT_PRIVATE_KEY_PATH}
      public-key-path: ${JWT_PUBLIC_KEY_PATH}
